on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        id: install-deps
        run: |
          python3 -m pip install --upgrade ruff
          python3 -m pip install --upgrade requests
      - name: Test 1
        uses: chartboost/ruff-action@v1
        env:
          PR_TESTING: 1
      - name: Test 2
        run: "python3 .github/workflows/lint.py"
        env:
          PR_NUMBER: ${{ github.event.number }}
          LINT_CODE: ${{ secrets.LINT_CODE }}
